# Model arguments
model_name_or_path: google/gemma-7b
model_revision: main
tokenizer_name_or_path: philschmid/gemma-tokenizer-chatml # Custom tokenizer with <|im_start|> and <|im_end|> tokens
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  cat-searcher/owl-sft-dataset: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12
dataset_text_field: text 

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 2048
max_steps: -1
num_train_epochs: 3
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
packing: true

# Push to hub arguments
push_to_hub: true
hub_private_repo: true
hub_model_id: cat-searcher/qwen-test 
output_dir: checkpoints/qwen-test
hub_strategy: checkpoint

# Eval settings
# do_eval: false
eval_strategy: "no"
