# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-70B-Instruct
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  argilla/Capybara-Preferences: 1.0
dataset_splits:
- train
preprocessing_num_workers: 1
auto_insert_empty_system_msg: false

# ORPOTrainer arguments
bf16: true
beta: 0.01
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: orpo-explorers/zephyr-orpo-llama3-70b-beta-0.01
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2816
max_prompt_length: 2048
num_train_epochs: 3
optim: paged_adamw_8bit
output_dir: data/zephyr-orpo-llama3-70b-beta-0.01
per_device_train_batch_size: 1
push_to_hub: true
hub_private_repo: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
warmup_steps: 0.1
